### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by omadson** [omadson/CKP8122#1]
### basic
 - [x] Matrix class
 - [x] multiplication of vector-matrix and matrix-vector

### direct Methods
 - [x] gauss elimination
 - [x] LU decomposition
 - [x] Cholesky decomposition (positive definide matrices)
  
### iterative methods
 - [x] Jacobi
 - [x] Gauss-Seidel
 - [x] successive over-relaxation
 - [x] conjugate gradients

### least square methods
 - [x] Gram-Schmidt
 - [x] QR decomposition using Householder
 - [ ] QR decomposition using Jacobi

### eigenvalues and eigenvectors of matrices
 - [ ] power method (regular, inverse and with displacement)
 - [ ] similarity transformations method (Householder + QR)
 
### final
 - [ ] singular value decomposition
